.github/workflows/release.yml
package.json

@stanleygjones Now we just need to set up the VSCE_PAT secret as described in https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing and you shouldn't need to manually publish new version of the plugin anymore.

Adds a release CI job

---

syntaxes/Major.tmLanguage

This PR adds the `flexible`, `stable`, `ignore`, and `label` keywords while removing extraneous Swift keywords such as `open`, `get`, `set`, `operator`, etc. 
Syntax highlighting should now be consistent with the [documentation](https://smartcontracts.org/docs/current/developer-docs/build/languages/motoko/language-manual/#keywords).
Fixes #15, #19

Add missing Motoko keywords and remove extra Swift keywords

---

.vscodeignore
syntaxes/Major.tmLanguage

Continuation of #23. The current TextMate language specification is almost directly based on Swift, so this PR fixes most of the remaining syntax highlighting and namespace issues.
This PR also adds a minimal `.vscodeignore` file as encouraged by the `vsce package` command. 
Works as expected on Ubuntu (WSL) using the latest version of VSCode.

Overhaul TextMate syntax highlighting

---

package-lock.json
package.json

Enables JSON Schema validation for `dfx.json` files.
[Relevant forum post](https://forum.dfinity.org/t/dfx-json-schema-is-finally-available/14668)
Future steps:
- Change the default schema URL to https://json.schemastore.org/dfx once available. 
- Prioritize using schema definition from `dfx schema` command output.

Add schema validation + autocompletion for dfx.json

---

package-lock.json
package.json
src/extension.ts
src/formatter.ts
src/utils.ts
syntaxes/Major.tmLanguage

This PR adds a custom Motoko code formatter which uses [prettier-plugin-motoko](https://github.com/dfinity/prettier-plugin-motoko) under the hood. It's possible to customize the formatter for individual Motoko projects using a [`.prettierrc` config file](https://prettier.io/docs/en/configuration.html). 
Although this functionality is also supported via the official [Prettier VS Code extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode), this integrated formatter will automatically update with the VS Code extension (compared to having to manually bump NPM dependencies otherwise). 
The formatter itself is a [work in progress](https://github.com/dfinity/prettier-plugin-motoko/issues/1). That being said, I'm hoping to get this out to users as early as possible …

Add basic code formatter

---

src/extension.ts

The VS Code extension currently has a tendency to nag the user about choosing a `mo-ide` entry point whenever `dfx.json` is missing from the project workspace... every single time the extension finishes loading... regardless of whether `mo-ide` is even available on your path. 
This PR hides the prompt if the user-configured `mo-ide` file is missing on your file system, which was probably the original intended behavior for this feature. 
Before looking into how this was implemented, I expected this fix to involve a partial rewrite of the extension. However, it turns out there was a simple, elegant solution. Hooray!

Show 'mo-ide' prompt only when language server is available on path

---

.github/workflows/release.yml

Replaces 'created' with 'published' in the release workflow ([relevant StackOverflow question](https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published)).

Use 'published' release type in GHA

---

README.md

The original badge provider appears to have significant stretches of downtime, so I just replaced it with an equivalent (custom-stylized) Shields.io badge.

Replace VS Marketplace badge provider with Shields.io

---

README.md
package.json
src/extension.ts
src/server/server.ts

- Support Vessel packages in projects without a `dfx.json` file
- Add "Restart Motoko language service" functionality for the TS LS
- Automatically use the TS LS when `dfx >= 0.11.1` or if no `dfx` version is specified
- Update the readme with information about the new language server

Improvements to new language server ("TS LS")

---

language-configuration.json

Removes the auto-closing behavior when typing `<`, since this often gets in the way of using the `<` or `<=` comparison operators. This simplified behavior is also more consistent with other languages in VS Code.

Remove angle brackets from auto-closing pairs

---

README.md
language-configuration.json
package-lock.json
src/extension.ts
src/server/preprocessMotoko.ts
src/server/server.ts

Adds compiler errors and warnings to Motoko files used by `dfx.json` canisters (and any dependencies of files opened in the editor).

Propagate type checking from currently open files and `dfx.json` entry points

---

package-lock.json
package.json
src/server/server.ts
tsconfig.json
utils/downloadBaseLibrary.js

Switches to using a cached version of the Motoko base library rather than potentially calling the GitHub API on extension startup.

Use cached Motoko base library

---

package-lock.json
package.json
src/server/server.ts

Validates the entire workspace on save (instead of only `dfx.json` canister entry points).

Validate entire workspace on save

---

package.json
src/server/server.ts

This new underscored file extension makes it possible to use Motoko syntax highlighting without type checking, such as when creating templates or using a preprocessor.
Resolves #51.

Syntax highlight `*.mo_` files

---

package.json
src/browser.ts

This PR is a first step toward supporting Motoko in browser-based environments such as [github.dev](https://github.dev/github/dev) and [vscode.dev](https://vscode.dev/).

Add basic web extension support

---

package-lock.json
package.json
src/server/server.ts

Encourages developers to try running `dfx deploy` if they run into the relatively common "canister alias not defined" error.

Clarify 'canister alias not defined' error message

---

package-lock.json
package.json

Two minor changes
- fixed "The latest version of `vsce` is 2.13.0 and you have 2.11.0" warning
- save space by hard-linking contents of `src/generated` to `out/generated`.
The former looked like low-hanging fruit.
The latter is important for me, as my Mac has a 256 GB disk that is almost full :-)
```
[nix-shell:~/vscode-motoko]$ ls -l out/generated
total 124668
-r--r--r-- 2 ggreif staff 22063062 Oct 23 02:31 moc.js
-r--r--r-- 2 ggreif staff 81300825 Oct 23 02:31 viperserver.jar
-r-xr-xr-x 2 ggreif staff 24292476 Oct 23 02:31 z3
```
The `package-lock.json` changes were obtained by running `npm audit fix`.

viper: tweaks

---

README.md
package-lock.json
package.json
src/extension.ts

Removes support for a configuring a global standalone language server, since this feature is no longer necessary and has the potential to cause confusion. 
This PR also updates `prettier-plugin-motoko` and applies changes from `npm audit fix`.

Drop support for standalone 'mo-ide' binary

---

package.json
src/extension.ts
src/server/server.ts
src/server/viper.ts

This captures the LSP's output and waits until it announces its listening port. Then the connection is set up towards that port.
- Avoids premature connect when the listening port is not ready yet. (This happened routinely on my Mac.)
- Also avoids the fixing of a port number for LSP.
- Also eliminates Viper-related junk from the distribution (reducing size) and reuses the artefacts that come with Viper itself.
_CAVEAT_: You'll need to install the "pre-release" Viper extension from the marketplace and (suggested) switch the tool download to `Nightly`.
Open issue:
- locate the `java` binary (there is an npm for that!)

LSP: wait till port is up and parse it

---

.gitignore
.vscodeignore
package-lock.json
package.json

Replaces `tsc` with `esbuild`, which reduces the package size from 70+ MB to around 9 MB. 
As an added benefit, the extension also builds about an order of magnitude more quickly than before.

Refactor to use `esbuild` bundler

---

package-lock.json
package.json
src/extension.ts
src/formatter.ts

Fixes a regression from #99 involving the position of the `prettier-plugin-motoko` Wasm file in the bundled output directory.

Fix formatter for bundled extension

---

package-lock.json
package.json
src/server/ast.ts
src/server/imports.ts
src/server/navigation.ts
src/server/server.ts
src/server/syntax.ts
src/server/utils.spec.ts
src/server/utils.ts

Implements ["Go to definition"](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition) functionality for local variables, type aliases, record literals, modules, and imports (including from Vessel / MOPS packages). 
This is a work-in-progress feature with lots of corner cases. Bug reports are welcome!

Go-to-definition support, first pass

---

src/extension.ts

Makes it possible to navigate the base library using virtual `mo:` URIs within VS Code. 
Improves the UX for go-to-definition when opening a project without a base library provided by Vessel or MOPS.

Add `mo:` URI handler for base library navigation

---

README.md
src/extension.ts
src/server/imports.ts
src/server/server.ts

Sorts and groups Motoko imports on pressing the ["Organize imports"](https://stackoverflow.com/questions/49919726/how-to-invoke-the-organize-imports-typescript-feature-in-visual-studio) key binding. 
Here is an overview of the current grouping and sorting rules:
- Sort alphabetically by path, import name, and then field name
- Move named module imports above explicit field imports for the same path
- Group by prefix (`ic:`, `canister:`, `mo:`, and then relative paths)
TODO:
- Automatically remove unused imports
Progress towards #123.

Implement 'organize imports' functionality

---

package-lock.json
package.json
src/server/server.ts

Detects `ic-mops` from local or global npm dependencies instead of `mops` from the system path. This makes it possible to use different MOPS versions for individual projects.

Resolve MOPS from local package.json dependencies

---

package-lock.json
package.json
src/server/server.ts

If an error occurs while loading package sources, the extension will now cache successful results when more than one package context (e.g. `mops.toml` or `vessel.dhall` file) exists in the workspace. 
Addresses #164.

Cache package sources during retry-on-save

---

package-lock.json
package.json
src/server/server.ts

This PR changes the extension to only type-check active tabs and canister entry points, providing a giant performance boost (on the order of 100x) for large-scale Motoko workspaces.

Improve performance for large workspaces

---

src/server/server.ts

Increases the debounce time between autosaving and type checking all canister entry points in the workspace (500 -> 1000 ms).

Improve performance when using autosave

---

src/server/server.ts

Fixes a bug which causes a Vessel or MOPS configuration file to override the source command defined by an adjacent `dfx.json` file.

Always prioritize package source command from dfx.json file

---

package-lock.json
package.json

Updates the bundled compiler and ships a bugfix for https://github.com/dfinity/motoko/issues/3822.

Bump moc to 0.8.3

---

language-configuration.json
package-lock.json
package.json
syntaxes/Major.tmLanguage

Fixes a regression which causes `<` and `>` characters to render as unclosed pairs when imbalanced.

Improve tokenization for operators with `<` and `>`

---

package-lock.json
package.json
src/server/server.ts

Replaces `// @testmode wasmer` with `// @testmode wasi` for compatibility with the upcoming `mo-test` command.
Context: https://github.com/dfinity/motoko-dev-server/pull/18.

Update unit test convention for compatibility with `mo-test`

---

package-lock.json
package.json
src/extension.ts
src/server/viper.ts

This PR includes a patch for the `viperTools` path so that the Motoko-san extension will work by default on [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). 
Context: [this forum conversation](https://forum.dfinity.org/t/motoko-san-code-level-verification-in-motoko/18171/3)

Add support for WSL

---

src/server/server.ts

Replaces "MOPS" with "Mops" for consistency with the project's current branding.

Update capitalization in Mops integration

---

package-lock.json
package.json
syntaxes/Major.tmLanguage

Fix 'catch' and 'do' keyword highlighting in VS Code 1.78+

---

package-lock.json
package.json
src/server/server.ts

Suggests adding canister dependencies in `dfx.json`, which is another common cause of the "canister alias not defined" error message.

Update "canister alias not defined" error message

---

package-lock.json
package.json
src/server/server.ts

Fixes a glob pattern corner case involving recursive symbolic links raised in #223.

Skip symbolic links when loading workspace files

---

src/common/connectionTypes.ts
src/extension.ts
src/server/server.ts

This PR adds an error message to help developers debug common issues with their `dfx.json` package configuration, Mops / Vessel installations, etc.

Add notification on Mops / Vessel package configuration error

---

README.md
package-lock.json
package.json
src/common/connectionTypes.ts
src/extension.ts
src/server/server.ts

Search, install and import packages from Mops.
v
After package select, adds package to `mops.toml`.
If active file is `*.mo` - adds import line.
------
Also now new package import added after the latest import of the same package, or after latest "mo:..." import.
For example:
```motoko
import Array "mo:base/Array";
import Local "./local";
```
add `Map` import from `map` package:
```diff
import Array "mo:base/Array";
+import Map "mo:map/Map";
import Local "./local";
```
add `Trie` import from `base` package:
```diff
import Array "mo:base/Array";
+import Trie "mo:base/Trie";
import Map "mo:map/Map";
import Local "./local";
```

Add "Import Mops Package..." command

---

package-lock.json
package.json
src/formatter.ts

This PR fixes several corner cases which are frequently encountered while upgrading from Prettier 2.x to 3.x in a local npm project. 
Since the VS Code extension uses Prettier 2 while local projects use Prettier 3, it was possible for plugins intended for the latest version to cause errors while using the IDE formatter. The extension now always uses a built-in Motoko plugin which works for both Prettier versions.

Improve formatting with Prettier 3.x

---

package-lock.json
package.json
src/candid/aaaaa-aa.did.ts
src/server/server.ts

This PR adds syntax highlighting for both `canister:` imports of `"type": "pull"` dependencies and `ic:aaaaa-aa` imports. 
Resolves #263.

Support canister aliases for `pull` dependencies and direct imports of management canister

---

package-lock.json
package.json
src/server/server.ts

Follow-up to #264. Gives priority to an existing `aaaaa-aa.did` file in the `.dfx/local/lsp` directory over the built-in default interface.

Prioritize existing management canister Candid file

---

README.md
src/extension.ts

Replaces `.ic0.app` with `.icp0.io` for Candid UI and uses the custom domain `play.motoko.org` for Motoko Playground.

Update canister URLs

---

package-lock.json
package.json
src/server/context.ts
src/server/server.ts

First step towards supporting multiple compiler versions. Makes it possible to use Motoko 0.10.4 while the ecosystem catches up with the breaking changes in 0.11.

Use moc.js 0.10.4 for dfx versions prior to 0.18.0

---

package-lock.json
package.json
src/server/server.ts

Removes warnings in downloaded package dependencies while continuing to show compiler errors.

Suppress compiler warnings in `.mops` and `.vessel` directories

---

package-lock.json
package.json

Tested and appears to work with the latest version. Splitting this into a separate PR both for the changelog and so we could roll this back if needed.

Bump `ic-mops` to latest version

---

package-lock.json
package.json
src/server/dfx.ts
src/server/server.ts

This PR adds support for `"type": "custom"` canisters with explicit canister IDs. 
Because these canisters are not included in `.dfx/local/canister_ids.json` or the `.dfx/local/lsp/` directory, a special case is required for these canisters.
Although this fixes compiler errors in the [Cycles Faucet](https://github.com/dfinity-lab/cycles-faucet) codebase, additional follow-up changes to the extension and/or `dfx` may be needed to generalize this to all possible cases (e.g. deploying with a `--specified-id` flag).

Support custom dfx canister principals

---

package-lock.json
package.json
src/extension.ts
src/server/motoko.ts
src/server/viper.ts

How to use this fix:
0. Make sure you have the "Viper v4.3.1" extension installed in VS Code, and that it has installed its dependencies (this happen via a prompt when you open e.g., an empty Viper file in VS Code with this extension installed). Verifying Viper files should work automatically upon saving .vpr files.
1. Setup the VS Code extension repo as follows:
```
git clone https://github.com/dfinity/vscode-motoko -b arshavir/serokell-ide-quick-fix
cd vscode-motoko
npm install
cd ..
```
2. Compile your custom version of the Motoko compiler into JS:
```
git clone https://github.com/serokell/motoko
cd motoko
nix-build -A js
```
This should print something like `/nix/store/x7amwi31gzavs8r7q89ljwwaksg5kqzw-moc.js` (which is a directory). Copy the internal JS file into a place that would be …

Draft: Fix minor issues to enable Serokell to use the IDE for local testing

---

package-lock.json
package.json
src/server/server.ts

Sometimes errors may occur when a user runs`mops install` because ext calls `mops sources` which starts with `mops install`, so we get two concurrent install processes. With `--no-install` flag this problem should go away.

Update mops and call `mops sources` with `--no-install` flag

---

package-lock.json
package.json
src/common/watchConfig.ts
src/extension.ts
src/server/server.ts

This PR fixes a `too many symbolic links encountered` error message which can prevent the extension from loading in repositories with a large number of symlinks (e.g. in a `node_modules` directory).

Fix corner case with test file discovery

---

syntaxes/Major.tmLanguage

Removes the `repeat` keyword from syntax highlighting (not a keyword in Motoko).

Remove extraneous keyword

---

.github/workflows/release.yml

Makes it possible for us to manually trigger the "Release" workflow (consistent with other DFINITY repositories).

Add `workflow_dispatch` for release CI

---

src/formatter.ts

Fixes an issue reported by @letmejustputthishere related to a trailing semicolon when specifying init args in a Candid file.

Remove trailing semicolons and commas in Candid formatter

---

src/server/handlers.ts
src/server/server.spec.ts

When using the language server included in vscode-motoko with Zed, distracting blank lines are displayed when the hint displayed on hover ends with a code snippet.
To avoid this, `trimEnd()` has been added within `codeSnippet`.

fix: trim trailing whitespace from Motoko code snippets

---

package-lock.json
package.json

Since this release includes significant changes (#347), the plan is to wait until early next week to deploy so that we can more quickly make follow-up changes if needed.

Update `moc` to 0.14.11

---

README.md
package.json
src/common/connectionTypes.ts
src/extension.ts
src/server/context.ts
src/server/deployer.ts
src/server/handlers.ts

This PR removes references to Motoko Playground in favor of referring to this feature in a more generic way.

Replace `motoko.deployPlayground` command with `motoko.deployTemporary`

---

src/server/navigation.ts
src/server/test/definition.spec.ts
test/definition/var.mo

Problem: Our work on Motoko broke go-to-definition for `var` declarations.
Solution: Fix `searchDeclaration` to properly handle ID in var declarations. Add a regression test.

[Chore] Fix go-to-definition for var

---

package-lock.json
package.json
src/server/navigation.ts
src/server/syntax.ts

Resolves https://github.com/dfinity/vscode-motoko/issues/376.
Because Motoko 0.15.1 uses a new `ValPF` AST node for object pattern fields, I updated the navigation logic accordingly.

Update `moc` to 0.15.1

---

package.json

Fixes a bug related to VS Code interpreting some variants as hexadecimal colors:

Deactivate color decorators for Motoko/Candid files
