dfinity/vscode-motoko

README.md
Seems like Swift is registered by Apple: https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html
=> Minor touchups to README

package-lock.json, package.json, syntaxes/Major.tmLanguage
Relevant PRs for the `with` keyword:
- dfinity/motoko#3367
- dfinity/motoko#3399
- dfinity/node-motoko#3
=> Add syntax highlighting for missing keywords

README.md
Updates the readme to account for changes leading up to the v0.4.0 release.
=> Update readme for v0.4.0

src/server/server.ts
Accounts for backslash characters and drive names in Windows file paths.
=> Improve file path handling on Windows

package-lock.json, package.json, src/server/server.ts
Ensures that a default version of the base library is loaded before Vessel packages.
=> Always add base library by default

package-lock.json, package.json
=> Update code formatter

package-lock.json, package.json, syntaxes/Major.tmLanguage
- Updates the Motoko code formatter to the latest version
- Removes a few extraneous keywords from the syntax highlighter
=> Miscellaneous

package-lock.json, package.json, src/server/ast.ts, src/server/imports.ts, src/server/information.ts, src/server/program.ts, src/server/server.ts, src/server/utils.ts
Adds basic type information on hover, along with a system to show documentation links for unique language features.
=> Basic type information and documentation links on hover

package-lock.json, package.json, src/server/server.ts
- Highlights the relevant AST node on hover (instead of duplicating the source code in the tooltip)
- Adds Motoko keywords to autocompletion
=> Tooltip and autocompletion UX improvements

package-lock.json, package.json, src/server/ast.ts, src/server/imports.ts, src/server/server.ts, src/server/syntax.ts, src/server/utils.ts
Includes local variable names in autocompletion results, along with a few other minor improvements.
=> Autocompletion for local variables

package-lock.json, package.json, src/server/server.ts, src/server/utils.ts
Increases readability when hovering over values with complex types.
=> Show formatted types on hover

package-lock.json, package.json, src/extension.ts
Uses `@viperproject/locate-java-home` in place of calling `java` from the system path.
=> Look up Java home directory using `viper-ide` logic

package.json, syntaxes/Major.tmLanguage, themes/FormalMotoko.tmTheme
=> Add TM for Formal Motoko 

.gitmodules
the `viper` branch in https://github.com/dfinity/motoko is merged (and thus deleted)
=> chore: Viper is on Motoko `master`

package.json, snippets.json
Includes basic Motoko snippets (adapted from #18).
=> Add basic snippets

snippets.json
=> Adjust code snippets

src/server/server.ts
Improves UX for editing `dfx.json` / `*.dhall` files when autosave is enabled.
=> Increase debounce time for Vessel and dfx configuration change listeners

package-lock.json, package.json, src/server/server.ts
=> Improve `vessel sources` error handling

package-lock.json, package.json, src/server/imports.ts, src/server/server.ts
Implements same-file doc comment tooltips in preparation for displaying base library documentation on hover.
=> Progress towards doc comments on hover

package-lock.json, package.json, src/server/server.ts
Automatically reloads MOPS and Vessel sources on editor file change to improve the UX in situations such as #148.
=> Improve error handling for MOPS and Vessel integrations

package-lock.json, package.json
Fixes various block comment formatting corner cases via https://github.com/dfinity/prettier-plugin-motoko/pull/80.
=> Bump formatter

package-lock.json, package.json
Includes `principal-2-actor` and `text-2-actor` conversion snippets.
=> Bump `motoko`

package-lock.json, package.json
See https://github.com/dfinity/node-motoko/pull/52.
=> Add more snippets

package-lock.json, package.json
(VS Code extension version 0.8.1, and `moc` version 0.8.0)
=> Bump to 0.8.1

package-lock.json, package.json, src/server/server.ts, src/server/utils.ts
This PR includes error code explanations from the `moc --explain` command directly in the VS Code extension:
Contribute new explanations here:
https://github.com/dfinity/motoko/tree/master/src/lang_utils/error_codes
=> Add error code explanation tooltips

package-lock.json, package.json
=> Adjust "Motoko: Deploy (20 minutes)" context menu item position

package-lock.json, package.json, syntaxes/Major.tmLanguage
Context: https://github.com/dfinity/motoko/pull/4003.
=> Add `composite` keyword

.github/workflows/tests.yml, package-lock.json, package.json, src/server/ast.ts, src/server/context.ts, src/server/imports.ts, src/server/navigation.ts, src/server/server.ts, src/server/syntax.ts
=> Implement "outline view" and "go to symbol" functionality

package.json, src/server/imports.ts, src/server/server.ts, src/server/syntax.spec.ts, src/server/syntax.ts
Adds support for classes, types, mutable variable fields, actors, and unnamed modules.
=> Outline view improvements

package-lock.json, package.json, src/server/server.ts
This PR makes a few adjustments to the type checking queue and fixes a subtle bug with the virtual file system logic.
Fixes #173.
=> Improve type checking UX

package-lock.json, package.json, src/server/server.spec.ts, test/cache/issue-340.mo
Depends on https://github.com/dfinity/motoko/pull/5048 and https://github.com/dfinity/node-motoko/pull/123.
Problem: We need to add a test to ensure the problem is resolved.
Solution: Add a case reproducing the problem and a test checking a double hover works.
=> [VSC-26] Add a regression test for issue #340

package-lock.json, package.json, src/server/ast.ts, src/server/handlers.ts, src/server/imports.ts, src/server/navigation.ts, src/server/syntax.spec.ts, src/server/test/completion.spec.ts, src/server/test/helpers.ts, test/completion/a.mo, test/completion/b.mo, test/completion/c.mo
* Use error recovery that is added in the https://github.com/dfinity/motoko/pull/4959 
* Add autocompletion for imported modules
This PR follows https://github.com/dfinity/vscode-motoko/pull/329
=> Add error recovery & module autocompletion (Serokell, Milestone 2)

package-lock.json, package.json
Includes changes from https://github.com/dfinity/node-motoko/pull/123.
=> Update `motoko` npm dependency

package-lock.json, package.json
Replaces [`vsce`](https://www.npmjs.com/package/vsce) with [`@vscode/vsce`](https://www.npmjs.com/package/@vscode/vsce).
=> Fix `vsce` deprecation warning

README.md, package.json, src/server/test/mock.ts
=> Remove "Legacy language server" configuration

README.md, package.json, src/extension.ts, src/server/test/mock.ts
Related to https://github.com/dfinity/motoko/pull/5075
=> chore: removes code invoking the old language server

vsmarketplace-proof.txt
Removes a temporary file introduced in #354.
=> Remove VS Marketplace verification file
